# See https://domluna.github.io/JuliaFormatter.jl/stable/ for a list of options
style = "blue"
always_use_return = false
trailing_comma = false
whitespace_in_kwargs = true
join_lines_based_on_source = true