prlp_allow_warm_start = true
vpolycut_priority = 99999
vpolycut_delay = false
vpolycut_min_gap_closed_increase = 0.01
prlp_solve_method = 1
vpolycut_max_cut_per_round = 150
disable_scip_cuts = true
vpolycut_max_consecutive_fail = 5
vpolycut_max_consecutive_stagnation = 10
n_leaves = 64
vpolycut_frequency = 0
