vpc_max_participating_round = 1
scip_enable_strong_branching_lookahead = false
scip_allow_restart = false
scip_node_limit = 1
vpc_frequency = 0
vpc_delayed = false
vpc_prlp_solve_method = 1
vpc_max_cut_per_round = 150
vpc_prlp_apply_beta_scaling = false
vpc_prlp_allow_warm_start = true
scip_max_root_cutting_plane_rounds = 1
vpc_prlp_min_gap_closed_increase = 0.01
vpc_min_restart = 0
vpc_n_leaves = 64
vpc_prlp_max_consecutive_fail = 5
scip_enable_cut_selection = false
scip_enable_heuristic = false
vpc_priority = 99999
scip_disable_scip_cuts = true
scip_time_limit = 3600
vpc_prlp_max_consecutive_stagnation = 10
