modes = [
    "vpc"
]
lp_solving_method = 4
instances = [
  "30n20b8",
  "beasleyC3",
  "binkar10_1",
  "bnatt400",
  "cod105",
  "cost266-UUE",
  "csched007",
  "exp-1-500-5-5",
  "gen-ip002",
  "glass4",
  "graph20-20-1rand",
  "graphdraw-domain",
  "icir97_tension",
  "mc11",
  "mcsched",
  "mik-250-20-75-4",
  "milo-v12-6-r2-40-1",
  "n5-3",
  "neos-1582420",
  "neos-3083819-nubu",
  "neos-3216931-puriri",
  "neos-3381206-awhea",
  "neos-3627168-kasai",
  "neos-911970",
  "neos17",
  "neos5",
  "ns1208400",
  "ns1830653",
  "nu25-pr12",
  "p200x1188c",
  "pg5_34",
  "pg",
  "ran14x18-disj-8",
  "reblock115",
  "rococoC10-001000",
  "roll3000",
  "seymour1",
  "sp150x300d",
  "timtab1",
  "tr12-30",
  "traininstance6",
  "uct-subprob"
]
random_seeds = [
  1597,
6829,
193,
619,
8179,
4507,
461,
1481,
7577,
4259
]
