struct TimeLimitExceededCollection <: Exception end
struct TimeLimitExceededBranchAndBound <: Exception end
struct LPSolNotBasic <: Exception end
struct LPSolNotOptimal <: Exception end
struct FailedDisjunctiveLowerBoundTest <: Exception end
struct FailedToProvePRLPFeasibility <: Exception end
struct PStarNotTight <: Exception end
struct BasestatZeroEncountered <: Exception end
struct LPError <: Exception end
struct TreeHasNoLeaf <: Exception end