vpc_max_participating_round = 1
scip_enable_strong_branching_lookahead = false
scip_allow_restart = false
scip_node_limit = 1
vpc_frequency = 0
vpc_delayed = false
scip_enable_conflict_analysis = false
vpc_prlp_solve_method = 1
vpc_max_cut_per_round = 200 
scip_enable_root_node_propagation = false
vpc_prlp_apply_beta_scaling = false
vpc_prlp_allow_warm_start = true
scip_max_root_cutting_plane_rounds = -1
vpc_prlp_min_gap_closed_increase = 0.0
vpc_min_restart = 0
vpc_point_collection_time_limit = 900
vpc_n_leaves = 64
vpc_prlp_max_consecutive_fail = 10
scip_enable_cut_selection = false
vpc_branch_and_bound_time_limit = 900
scip_enable_heuristic = false
vpc_prlp_time_limit = 900
vpc_priority = 99999
scip_disable_scip_cuts = false 
scip_time_limit = 7200
vpc_prlp_max_consecutive_stagnation = 99999
