julia_depot_path = "/scratch/htc/gtjusila/julia"
template_file = "job_script_template.sh"
path_to_script = "/home/htc/gtjusila/Project/VPolyCut/scripts/run_single_experiment.jl"
instances_base_path = "/home/htc/gtjusila/Project/VPolyCut/instances_data"
